name: projectscoid
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  animated_text_kit: ^4.2.1
  adaptive_breakpoints: ^0.1.1

  badges: ^2.0.2
  # blockquote: ^0.0.1  unsound-null-safety
  bubble: ^1.2.1

  cookie_jar: ^3.0.1
  connectivity_plus: ^2.2.1
  #camera: ^0.9.4+14
  crypto: ^3.0.1
  carousel_slider: ^4.0.0


  data_tables: ^1.4.0
  dio: ^4.0.4
  dio_cookie_manager: ^2.0.0
  device_info_plus: ^3.2.2
  date_format: ^2.0.5

  encrypt: ^5.0.1
  equatable: ^2.0.3
  expandable: ^5.0.1

  #firebase_core: ^1.12.0
  #firebase_messaging: ^11.2.6
  #file_picker: ^4.4.0
  fluro: ^2.0.3
  flutter_speed_dial: ^5.0.0+1
  flutter_slidable: ^1.2.0
  #flutter_masked_text: ^0.8.0   unsound-null-safety
  flutter_tags: ^1.0.0-nullsafety.1
  #flutter_local_notifications: ^9.3.2
  flutter_html: ^2.2.1
  flutter_barcode_scanner: ^2.0.0
  flutter_widget_from_html_core: ^0.8.5+1
  flutter_widget_from_html: ^0.8.5
  #flutter_icons: ^1.1.0  unsound-null-safety
  #flutter_downloader: ^1.7.2
  fluttertoast: ^8.0.8
  flutter_emoji: ^2.4.0
  #flutter_credit_card: ^0.1.4
  flutter_fgbg: ^0.1.0
  flutter_easyloading: ^3.0.3
  filesize: ^2.0.1
  flutter_rating_bar: ^4.0.0
  font_awesome_flutter: ^9.2.0

  getwidget: ^2.0.5

  html2md: ^1.2.5
  http: ^0.13.4
  html: ^0.15.0
  horizontal_data_table: ^3.6.1+1

  intl: ^0.17.0
  image: ^3.1.3


  json_annotation: ^4.4.0


 #koukicons: ^2.0.3 unsound-null-safety

  logging: ^1.0.2
  loading_animations: ^2.2.0
  #load_toast: ^2.0.0+1 unsound-null-safety
  #line_awesome_icons: ^2.0.0
  line_awesome_flutter: ^2.0.0

  markdown: ^4.0.1
  mime: ^1.0.1

  notification_permissions: ^0.6.1
  notustohtml: ^1.0.0-rc.1
  network_to_file_image: ^3.1.0

  path: ^1.8.0
  path_provider: ^2.0.9
  photo_view: ^0.13.0
  percent_indicator: ^4.0.0
  #permission_handler: ^9.2.0
  provider: 6.0.2
  pointycastle: ^3.5.1
  package_info_plus: ^1.4.0
  platform: ^3.1.0

  recase: ^4.0.0
  random_string: ^2.3.1
  rect_getter: ^1.1.0
  record_mp3: ^3.0.0
  record: ^3.0.2

  string_mask: ^1.0.0
  #smooth_star_rating: ^1.1.1 unsound-null-safety
  sqflite: ^2.0.2
  #splashscreen: ^1.3.5 unsound-null-safety
  easy_splash_screen: ^1.0.3
  sprintf: ^6.0.0
  shared_preferences: ^2.0.13
  #searchable_dropdown: ^1.1.3 unsound-null-safety
  dropdown_search: ^2.0.1
  share_plus: ^3.1.0
  screenshot: ^1.2.3
  scroll_to_index: ^2.1.1
  scrollable_positioned_list: ^0.2.3

  transparent_image: ^2.0.0
  timeago: ^3.2.2
  timeline_tile: ^2.0.0

  video_player: ^2.2.18

  #websocket_manager: ^0.2.2 unsound-null-safety
  ya_websocket: ^1.0.2
  webview_flutter: ^2.0.4
  webview_cookie_manager: ^2.0.6
  wakelock: ^0.6.1+1

  youtube_player_flutter: ^8.0.0

  #zefyrka: ^1.0.10

  # Fail
  camera: ^0.9.4+14

  firebase_core: ^1.12.0
  firebase_messaging: ^11.2.6
  file_picker: ^4.4.0
  flutter_local_notifications: ^9.3.2
  flutter_downloader: ^1.7.2

  image_picker: ^0.8.4+9
  image_gallery_saver: ^1.7.1

  just_audio: ^0.9.20

  permission_handler: ^9.2.0

  zefyrka: ^1.0.10

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  rxdart: ^0.26.0
  url_launcher: ^6.0.2
dev_dependencies:
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
